//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progress.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Progress.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente não encontrado..
        /// </summary>
        public static string CLIENTE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("CLIENTE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ inserido não é válido. Digite novamente..
        /// </summary>
        public static string CNPJ_INVALIDO {
            get {
                return ResourceManager.GetString("CNPJ_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do produto é  inválido. Digite novamente..
        /// </summary>
        public static string CODIGO_PRODUTO_INVALIDO {
            get {
                return ResourceManager.GetString("CODIGO_PRODUTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data da próxima visita não pode ser antes do dia de hoje..
        /// </summary>
        public static string DATA_PROXIMA_VISITA_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_PROXIMA_VISITA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição não pode estar vazia. Digite novamente..
        /// </summary>
        public static string DESCRICAO_VAZIA {
            get {
                return ResourceManager.GetString("DESCRICAO_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço não pode ser vazio ou nulo. Digite novamente..
        /// </summary>
        public static string ENDERECO_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As flags devem ser passadas como 1 ou 0.  Digite novamente.
        /// </summary>
        public static string FLAG_INVALIDA {
            get {
                return ResourceManager.GetString("FLAG_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Fantasia não pode ser vazio ou nulo.  Digite novamente.
        /// </summary>
        public static string NOME_FANTASIA_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_FANTASIA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do produto não pode estar vazio ou nulo. Digite novamente..
        /// </summary>
        public static string NOME_PRODUTO_VAZIO {
            get {
                return ResourceManager.GetString("NOME_PRODUTO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto não encontrado. Digite outro código..
        /// </summary>
        public static string PRODUTO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("PRODUTO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Razão Social não pode ser vazia ou nula.  Digite novamente.
        /// </summary>
        public static string RAZAO_SOCIAL_INVALIDA {
            get {
                return ResourceManager.GetString("RAZAO_SOCIAL_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone inválido.  Digite novamente.
        /// </summary>
        public static string TELEFONE_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor para o produto inváldio, não pode ser menor ou igual a zero. Digite novamente..
        /// </summary>
        public static string VALOR_PRODUTO_INVALIDO {
            get {
                return ResourceManager.GetString("VALOR_PRODUTO_INVALIDO", resourceCulture);
            }
        }
    }
}
